services:
  - type: web
    name: enru-social-backend-testing
    runtime: docker # Ensure this is set to docker
    dockerContext: . # This tells Render to look in the main folder
    dockerfilePath: ./Dockerfile # Ensure this matches your file name
